//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int AppointmentId { get; set; }
        public int PatientId { get; set; }
        public int DoctorId { get; set; }
        public System.DateTimeOffset AppointmentDate { get; set; }
        public System.DateTimeOffset AppointmentTime { get; set; }
        public string AppointmentDuration { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual Patient Patient { get; set; }
        public void getDetails()
        {
            Console.WriteLine("Patients: ");
            var patients = new Patient();
            patients.PatientList();
            Console.WriteLine("Enter Patient Id : ");
            PatientId = Convert.ToInt32(Console.ReadLine());

            Console.WriteLine("Doctors : ");
            var doctors = new Doctor();
            doctors.DoctorList();
            Console.WriteLine("Enter Doctor Id: ");
           DoctorId = Convert.ToInt32(Console.ReadLine());

            Console.WriteLine("Enter Appointment Date: ");
            AppointmentDate = System.DateTimeOffset.Parse(Console.ReadLine());
            Console.WriteLine("Enter Appointment Time: ");
            AppointmentTime = System.DateTimeOffset.Parse(Console.ReadLine());
            Console.WriteLine("How much time it would take?");
            AppointmentDuration = Console.ReadLine();


        }
    }
}
