//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagement
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    
    public partial class Patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patient()
        {
            this.Appointments = new HashSet<Appointment>();
            this.DrugTimings = new HashSet<DrugTiming>();
            this.Prescriptions = new HashSet<Prescription>();
            this.HealthcareAssistants = new HashSet<HealthcareAssistant>();
        }
    
        public int PatientId { get; set; }
        public string PatientFirstName { get; set; }
        public string PatientLastName { get; set; }
        public string PatientDisease { get; set; }
        public int PatientAge { get; set; }
        public string PatientGender { get; set; }
        public string PatientAddress { get; set; }
        public System.DateTimeOffset RegistrationDate { get; set; }
        public string MobileNumber { get; set; }
        public Nullable<int> RoomId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointment> Appointments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DrugTiming> DrugTimings { get; set; }
        public virtual Room Room { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prescription> Prescriptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HealthcareAssistant> HealthcareAssistants { get; set; }
        
        public void getDetails()
        {
            Console.WriteLine("Enter the name of the Patient");
            PatientFirstName = Console.ReadLine();
            Console.WriteLine("Enter the surname of the Patient");
            PatientLastName = Console.ReadLine();
            Console.WriteLine("Please summarize the problem ");
            PatientDisease = Console.ReadLine();
            Console.WriteLine("Enter the age of the Patient");
            PatientAge = Convert.ToInt32(Console.ReadLine());
            Console.WriteLine("Enter the gender of the Patient");
            PatientGender = Console.ReadLine();
            Console.WriteLine("Enter the address of the Patient");
            PatientAddress = Console.ReadLine();
            Console.WriteLine("Enter today's date");
            RegistrationDate = System.DateTimeOffset.Parse(Console.ReadLine());
            Console.WriteLine("Enter the Mobile number of the Patient");
            MobileNumber = Console.ReadLine();


        }
         public   void PatientList()
        {
            var db = new HospitalManagementDbEntities();
            var patientList = db.Patients;
            try
            {
                foreach (var p in patientList)
                {
                    Console.WriteLine("Id: " + p.PatientId + "Name : " + p.PatientFirstName);
                }
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
            }
        }

    }




}

