//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prescription
    {
        public int PrescriptionId { get; set; }
        public int PatientId { get; set; }
        public int DoctorId { get; set; }
        public string PrescriptionDetails { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual Patient Patient { get; set; }
        public void getDetails()

        {
            var patient = new Patient();
            var doctor = new Doctor();
            var drug = new Drug();
            Console.WriteLine("Enter the below prescription details");
            Console.WriteLine("Patients Details ");
            patient.PatientList();
            Console.WriteLine("Enter PatientId : ");
           PatientId = Convert.ToInt32(Console.ReadLine());
            Console.WriteLine("Doctors Details");
            doctor.DoctorList();
            Console.WriteLine("Enter DoctorId:");
            DoctorId = Convert.ToInt32(Console.ReadLine());
            Console.WriteLine("Enter the prescription Details");
            PrescriptionDetails = Console.ReadLine();

            
           
            



        }
    }
}
